### PR TITLE
fix protein construct names

### PR DESCRIPTION
**Pull request by jbloom**
In the last pull request, the strain names in the protein constructs had `/` characters replaced with `_` which made them no longer match the repo. This pull request fixes that by making a small tweak to the `design_H3_HAconstructs.ipynb` notebook and then running it to write FASTAs in `non-pipeline_analyses/library_design` with the correct strain names.

@ckikawa, can you review and merge?

### CODE REVIEW

**Comment by ckikawa** [comment]
@jbloom I think this looks good, but I'm hesitant to merge since I made a few changes to this notebook in an effort to exactly match the strain names to those output in the new tree from the Nextstrain seasonal-flu build I made. I'm just re-running the pipeline now with all those new strain names, then I can add these changes as a commit on that branch, if that sounds OK?

**Comment by jbloom** [comment]
Sounds good. Just remember to try to keep whatever changes you are making small and modular and make pull requests frequently with your updates to keep everything synced.

**Comment by ckikawa** [comment]
@jbloom yes I've been trying to keep that in mind, but in the process of trying to unify names I've sort of ended up making a bunch of commits across a variety of notebooks. Sorry in advance... if it's helpful to review together, let me know.

**Comment by jbloom** [comment]
Closed in lieu of #10

**Pull request closed without merging**
