### PR TITLE
rename strains

### PR DESCRIPTION
**Pull request by ckikawa**
This pull request closes issues #5, #6, and #7, which all have to do with strain naming inconsistencies. I used a Python script to do a string search-and-replace in the `data` and `library_design` subdirectories. I then re-ran the pipeline to produce new results with the re-named strains. 

Details for each issue:
* For #5 regarding `A/SOUTH_AFRICA/R07876/202023` : this is how the strain is named in GISAID. It was collected in 2023, so we can assume the trailing year `202023` is a typo. I've changed this to `A/SOUTH_AFRICA/R07876/2023`
* For #6 regarding `A/South_Africa/KO56863/2023` : I think this strain was named with an 'O' in Nextclade (?), otherwise, potentially names could have changed in between the two times I used the GISAID ID to pull this sequence from GISAID? I did a quick alignment to check nucleotide sequences were the same from my initial download for cloning and the recent download for tree building, and they are the same sequence. I've changed this to `A/South_Africa/K056863/2023`
* For #7 regarding `A/Saint-Petersburg/RII-MH144113/2023` : I think the discrepancy could be from any of the sources listed for #6. I did a quick alignment to check nucleotide sequences were the same from my initial download for cloning and the recent download for tree building, and they are the same sequence. I've changed the name of this sequence to `A/Saint-Petersburg/RII-MH144112/2023`

### CODE REVIEW

**Comment by jbloom** [comment]
@ckikawa, can you also add the `Nextstrain` JSON that was used to design the libraries and matches the fixed strain names to the repo along w README explanation? The original source of this issue was mismatch between Nextstrain JSON and strain names, and in order to make sure that is fixed the JSON also has to be part of the repo (and should be as it was a critical part of the library design). Really, any scripts / code / data / explanation used for library design should be in repo.

**Comment by jbloom** [comment]
I think this looks better. But the README has a bunch of broken links where it says things like `.non-pipeline_analyses/library_design/results/2023-2024_H3_library_protein_HA1.fasta` (there are a lot of links like this).

That is not a valid link, it needs to be either `./non-pipeline_analyses/library_design/results/2023-2024_H3_library_protein_HA1.fasta` or `non-pipeline_analyses/library_design/results/2023-2024_H3_library_protein_HA1.fasta`

**Comment by ckikawa** [comment]
@jbloom Ah, thanks for catching that! Links should all be fixed across the main directory README and the new `library_design` README. Also adding a strain name-related correction to the barcode construct design notebook.

**Comment by huddlej** [comment]
@ckikawa It looks like the GISAID record for `A/South Africa/K056863/2023` was renamed from `A/South Africa/KO56863/2023` after we first accessed it. If you look at the list of gene sequence identifiers for that isolate id (EPI_ISL_18161070), they all still have the original name of `A/South Africa/KO56863/2023` (with the capital "O").

**Pull request merged**
